### ISSUE TITLE
How to list pods from specific deployment?

### ISSUE THREAD

**Issue by thumbsized** [godaddy/kubernetes-client#109]
I am trying to list pods form specific deployment. On the docs it says it is supported on the rc(NOT deployment) but that does not work for me. I can list pods via `kube.core.namespace.pods.get()` only.

**Comment by silasbw** [comment]
You're correct -- we didn't implement that shortcut for `deployments`.  We should.  If you have time to take a first pass at a PR, that'd expedite getting it added.

**Comment by ivanjaros** [comment]
Sorry, I'm not nodejs guy. I can navigate my way around js but nodejs is out of my expertise.

**Comment by ryuheechul** [comment]
You should be able to do that with https://github.com/Rainist/k8s-ops

**Comment by silasbw** [comment]
This isn't something we plan on supporting.  There are other good higher-level libraries for doing it (*e.g.*, the one pointed out in this thread).
