### ISSUE TITLE
Label added to deployment added to rc instead

### ISSUE THREAD

**Issue by ivanjaros** [godaddy/kubernetes-client#111]
I have an existing deployment and I tried to add new label and update the deployment via:

```
GKE.prototype.update = function(json, successCallback, failureCallback) {
  var success = successCallback || console.log;
  var error = failureCallback || console.error;

  var type = this.getType(json);
  var exec = type === 'deployments' ? this.kube.extensions : this.kube.core;

  exec.namespaces[type](this.getName(json)).patch({ body: json }, function(err, result) {
    if (err) {
      error(err);
    } else {
      success(result);
    }
  });
};
```

after successful submission I have noticed that the deployment is the same, but a new replication controller was created with the new label.

This is unexpected behavior. How can I update the deployment properly?

**Comment by ivanjaros** [comment]
Sorry, I meant Replica Set, not Replication Controller.

**Comment by silasbw** [comment]
That is unexpected, but I'm having trouble reproing.  The below snippet logs the expected value (the Deployment manifest with the `foo: 'bar'` label):

```js
const Api = require('kubernetes-client');
const extensions = new Api.Extensions(Api.config.fromKubeconfig());
extensions.ns.deployments('nginx-deployment-0').patch({
  body: {
    metadata: {
      labels: {
        foo: 'bar'
      }
    }
  }
}, (err, res) => {
  if (err) throw err;
  console.log(res);
});
```

and `kubectl` poking confirms:

```
$ kubectl get deploy --show-labels
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       LABELS
nginx-deployment-0   5         5         5            0           10m       app=nginx,foo=bar
$ kubectl get rs --show-labels
NAME                            DESIRED   CURRENT   READY     AGE       LABELS
nginx-deployment-0-3351907313   5         5         0         11m       app=nginx,pod-template-hash=3351907313
```


Can you try a simpler example to confirm the buggy behavior you're seeing?

Also, this might help reduce the code you need to write to determine the right API group, and Object type:  https://github.com/godaddy/kubernetes-client#using-the-correct-api-group-and-version

**Comment by silasbw** [comment]
@ivanjaros were you able to resolve your issue?

**Comment by ivanjaros** [comment]
I haven't touchet it since and it looks I won't be needing to. Since you haven't had that issue I'll close this.
