### ISSUE TITLE
Differences between Extensions and APIs when sending yaml/json configuration

### ISSUE THREAD

**Issue by dackers86** [godaddy/kubernetes-client#113]
I am struggling with the difference between post and patch on different modules, so far...

I can post using the API (but not patch)...

const api = new k8s.Api({config})
api.group(manifest0).ns.kind(manifest0).patch({ body: manifest0 }

Error: 'the server does not allow this method on the requested resource'

---------------------------

I can patch (deployments only) but not post. Services as an example returns the same error on both post and patch...

const ext = new k8s.Extensions({config})
ext.namespaces.deployments(project_name) .patch({ body: body}, () => {response})

Error: 'the server does not allow this method on the requested resource'

**Comment by silasbw** [comment]
Can you provide a more complete example?  One that I can run?  Here's how I tried to repro your issue:

```js
const async = require('async');
const api = require('kubernetes-client');
const core = new api.Core(api.config.fromKubeconfig());

const body = {
  kind: 'Service',
  metadata: {
    name: 'test-service'
  },
  spec: {
    ports: [{ protocol: 'TCP', port: 8080 }]
  }
};

const patch = {
  metadata: {
    labels: {
      patchedIn: 'Hello-world'
    }
  }
};

async.waterfall([
  next => core.ns.services('test-service').delete(() => next()),
  next => core.ns.services.post({ body }, next),
  (service, next) => {
    core.ns.services(service.metadata.name).patch({ body: patch }, (err, res) => {
      if (err) return next(err);
      console.log(`Patched ${ JSON.stringify(res.metadata.labels) }`);
      next();
    });
  }
], err => {
  if (err) throw err;
});
```

This logs `Patched {"patchedIn":"Hello-world"}`.

**Comment by silasbw** [comment]
Closing because I haven't heard back -- happy to re-open if your problem persists @dackers86.
