### ISSUE TITLE
Cluster level queries

### ISSUE THREAD

**Issue by andrewklau** [godaddy/kubernetes-client#12]
Are there plans to support queries to cluster level resources queries

eg.
/api/v1/resourcequotas
/api/v1/replicationcontrollers

**Comment by silasbw** [comment]
Yeah, we should support this.  Here's the PR https://github.com/godaddy/kubernetes-client/pull/14.  Is this array missing any resources exposed at the cluster-level?

https://github.com/godaddy/kubernetes-client/pull/14/files#diff-9ccb9b0bdd7e6cd41dfc6512731c2719R42

**Comment by andrewklau** [comment]
There's also namespaces, pods and podtemplates at the cluster level

**Comment by silasbw** [comment]
Good catch: I added pods and podtemplates. we already expose namespaces (https://github.com/godaddy/kubernetes-client/blob/master/lib/api.js#L63)

**Comment by silasbw** [comment]
@andrewklau we published version 2.0.0 with the cluster-level support.  We hope it's helpful.
