### ISSUE TITLE
How would I delete a service, replica set, deployments and pods using this API

### ISSUE THREAD

**Issue by anuiq** [godaddy/kubernetes-client#120]

**Comment by anuiq** [comment]
for(i=0 ;i< res.length;i++)
    {
        delete res[i]['kind'];
        delete res[i]['apiVersion'];
        //delete res[i]['metadata'];
        if (res[i].items != null) {
            for (j = 0; j < res[i].items.length; j++) {
                delete res[i].items[j].spec;
                var labels ={};
                labels=res[i].items[j].metadata.labels;
                if(labels != undefined){
                    if(labels.hasOwnProperty('AppName')) {
                        if (res[i].items[j].metadata.labels['AppName'] == req.params.app) {
                            statuses[res[i].items[j].metadata.uid] = res[i].items[j].metadata.name;
                            core.ns(res[i].items[j].metadata.namespace).delete(res[i].items[j].metadata.uid);

                        }

                    }
                }

            }

        }   


I was trying to use this following line to remove the UID. This is executed in a loop and                          core.ns(res[i].items[j].metadata.namespace).delete(res[i].items[j].metadata.uid);

This throws a ----  return cb(error);
             ^

TypeError: cb is not a function

**Comment by TWood67** [comment]
HI @anuiq, the `delete` method expects a callback function:
https://github.com/godaddy/kubernetes-client/blob/b2df4484682d7c8070ad40452a804354c0e903c7/lib/base.js#L81

You'll want something like this:
```javascript
core.ns(res[i].items[j].metadata.namespace).delete(res[i].items[j].metadata.uid, function (err, res) {
  // check for err
  // do something with the results
});
```

**Comment by TWood67** [comment]
Since you're in a for loop, I would recommend using the `async` library. It will be very difficult to manage async calls in a standard for loop.

**Comment by anuiq** [comment]
Thanks @TWood67. I have added the print at the end and now the error has gone away but I still think there is some problem with my implementation. 
I changed it to 
                            core.ns.services.delete(res[i].items[j].metadata.name ,print);
I am looking to delete a service named 'alm-docker-test-22' however it throws this error: 
{ Error: services "alm-docker-test-22" not found
    at /Users/duai/Documents/backendtroubleshooting/node_modules/kubernetes-client/lib/base.js:9:21
    at Request.request [as _callback] (/Users/duai/Documents/backendtroubleshooting/node_modules/kubernetes-client/lib/api-group.js:101:7)
    at Request.self.callback (/Users/duai/Documents/backendtroubleshooting/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/duai/Documents/backendtroubleshooting/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/duai/Documents/backendtroubleshooting/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16) code: 404 }
{
  "code": 404
}
The problem is that the service exists. if I go to my Kubernetes dashboard or the cluster, I do have a service named "alm-docker-test-22". 
![screen shot 2017-06-28 at 2 22 14 pm](https://user-images.githubusercontent.com/15898853/27660948-3c67984e-5c0d-11e7-973b-4365de448ce2.png)

**Comment by TWood67** [comment]
Could you verify that the cluster endpoint and namespace are correct? It looks like you'll want something like:
```javascript
const Api = require('kubernetes-client');
const core = new Api.Core({
  url: 'your-k8s-api-server.com',
  version: 'v1', 
  namespace: 'pipe'
});
core.ns.services.delete('alm-docker-test-22', function(err, result) {
  //do stuff
});
```

**Comment by anuiq** [comment]
I got the services to work. I was missing a namespace value. 
core.ns(namespaceValue).svc.delete({name: res[i].items[j].metadata.name, labelSelector: 'appName: alm-docker-test' }, print);

Thank you
