### ISSUE TITLE
URL for watching jobs

### ISSUE THREAD

**Issue by bryanlarsen** [godaddy/kubernetes-client#123]
Is there a clean way to watch jobs?

The K8s URL is `/apis/batch/v1/watch/namespaces/{namespace}/jobs/{name}`  (https://kubernetes.io/docs/api-reference/v1.6/#watch-47)

To get it to actually use that URL, I fiddled the version:

```
const batchWatch = new K8s.Batch({
  version: 'v1/watch',
  ...
});

const stream = batchWatch.ns.jobs('foo').get();
```

Is there supposed to be a better way of doing this?

**Comment by silasbw** [comment]
There should be a better way-- we don't support that (newish) way of watching resources.  The older way is documented in the README.md [1].  I'll create a more general issue for supporting this.  :heart: :heart: :heart: if you want to take a pass at implementing it.

Sorry for the late reply.  A bunch of vacations and then playing catch up.

[1]: https://github.com/godaddy/kubernetes-client#watching-and-streaming

**Comment by silasbw** [comment]
kubernetes-client supports all the `watch` paths as of version 5.X.X.
