### ISSUE TITLE
TLSWrap.onread error while using Api.config.fromKubeconfig()

### ISSUE THREAD

**Issue by davideagle** [godaddy/kubernetes-client#125]
I'm trying to get a services from kubernetes by passing kubeconfig to Api.config.fromKubeconfig() but I receive the following error:

*Error*
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1007:11)
    at TLSWrap.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

*Sample Code multible services*

```javascript
const Api = require('kubernetes-client');
const kubeconfig = Api.config.loadKubeconfig(
  expandHomeDir('~/.kube/kubeconfig')
);
const core = new Api.Core(Api.config.fromKubeconfig(kubeconfig));

function getKubeCoreService(){
  core.services.get(getServices);
}

function getServices(err, result){
  console.log(err);
}
```

How ever if I only request one service it executes without errors

*Sample Code single service*

```javascript
const Api = require('kubernetes-client');
const kubeconfig = Api.config.loadKubeconfig(
  expandHomeDir('~/.kube/kubeconfig')
);
const core = new Api.Core(Api.config.fromKubeconfig(kubeconfig));

function getKubeCoreService(){
  core.services('servicename').get(getServices);
}

function getServices(err, result){
  console.log(err);
}
```

**Comment by silasbw** [comment]
@davideagle what version of kubernetes are you running?

I can't find the older API docs, but I *think* I remember you can only watch resources (*i.e.*, read Events from the endpoint) from the base API paths (e.g., /api/v1/services).  The ECONNRESET is a strange error, however.

If you want to read the manifests for all the Services see: https://github.com/godaddy/kubernetes-client/issues/93

**Comment by davideagle** [comment]
Getting multible services code works fine if it is run within kubernetes (using new Api.Core(Api.config.getInCluster()); ), however if I run the code from my workstation using loadKubeconfig instead I can only fetch a single service otherwise I get thrown the ECONNRESET

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by silasbw** [comment]
If this is still happening with a recent version of kubernetes-client and Kubernetes, let us know and we'll re-open.  Better would be a confirmed repro with minikube (that makes is easier for us to repro and fix).

**Comment by muralov** [comment]
The error also appearing for us too for the similar scenario.
