### ISSUE TITLE
Add support for /watch/ endpoints

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#128]
The best practice for watching events is to use the new API endpoints (*e.g.*, https://kubernetes.io/docs/api-reference/v1.7/#watch-64).  See https://github.com/godaddy/kubernetes-client/issues/123 for more motivation.

Guidance:
- Create a new `Watch` object that extends [`ContainerBaseObject`](https://github.com/godaddy/kubernetes-client/blob/master/lib/container-base-object.js)
- Add a `Watch` object to each `ApiGroup`.  See the how `ApiGroup` adds `.namespace` in [`constructor`]( https://github.com/godaddy/kubernetes-client/blob/master/lib/api-group.js#L9)
- Add unit tests and integration tests

**Comment by carldanley** [comment]
👍 Was just looking for this earlier today! Would be excellent to have this support!

**Comment by Pupix** [comment]
You guys still working on this? It's been like 4 months...

**Comment by silasbw** [comment]
We're working on a longer term solution to convert swagger docs to a kubernetes-client implementation.  We're not directly working on watch endpoints, but they would be covered by that longer term work.  If you have time, implementing the watch endpoints as described above would be a helpful shorter term solution.

**Comment by Pupix** [comment]
I could do that, but should I? How far off is your prediction on getting the swagger implementation done?  1 week? 1 month? 1 year?

**Comment by silasbw** [comment]
I'm shooting to have something to review by Jan 1st, but let's round up to 1 month.

**Comment by Pupix** [comment]
That's good. It's not that long, I can wait. 👍

**Comment by silasbw** [comment]
@Pupix do you want to give feedback on https://github.com/godaddy/kubernetes-client/pull/162 ?

**Comment by silasbw** [comment]
This is implemented in 5.X.X
