### ISSUE TITLE
Use swagger specs for generating object chains

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#129]
The [Python client](https://github.com/kubernetes-incubator/client-python) does something similar by leverage code generated by swagger-codegen.

kubernetes-client could use [swagger-js](https://github.com/swagger-api/swagger-js) to generate code dynamically using swagger specs distributed with kubernetes-client or using swagger specs hosted on the kube-apiserver.

**Comment by Pupix** [comment]
Does it really have to be this verbose?

```js
const kubernetes = require('kubernetes-client');
const spec = require('./swagger-1.8.json');
const http = new kubernetes.Request(kubernetes.config.fromKubeconfig());
const client = new kubernetes.SwaggerClient({ spec, http });
```

Using the above example, I should somehow find the `swagger.json` file for my kubernetes version, then initialize the Request and finally create the `SwaggerClient`.

Is it not possible for the module to come with predefined swagger files for X kubernetes versions? Or can't I just specify the kubernetes version I am using? Or can't it find the correct swagger file from my server?

Cheers,
Pupix

**Comment by silasbw** [comment]
Consider this PR the "primitives" we'd use to swagger support: the API contract of the generated client and the implementation of the code that generates it.  So, I think I agree with what you're suggesting:

* No, it doesn't need to be this verbose :smile: 
* Yes we should ship with predefined clients; and
* yes make async client creation easy by pointing at the kube-apiserver swagger.json.

If you have time to implement a "higher-level" API for the swagger stuff, we'd :heart: that.  It would be useful to have an example of what that API contract might be (and discuss it); and also to have a concrete implementation to work from (even if it wasn't perfect).

**Comment by silasbw** [comment]
This is complete.
