### ISSUE TITLE
Call to remove label from the pod

### ISSUE THREAD

**Issue by shekharupland** [godaddy/kubernetes-client#130]
Is there a support to patch pod, I am looking to remove certain labels from a given pod. 

I am trying to pass something like this in patch : 
body: {op:"remove", path: "/metadata/labels/op"}

but it doesn't seem to be working.

Any advice??

**Comment by TWood67** [comment]
Hi @shekharupland, are you providing the correct `Content-Type` header? We default to `application/strategic-merge-patch+json` which you can see here: https://github.com/godaddy/kubernetes-client/blob/69a6509e60fada97401ec444a759d03adadf205a/lib/api-group.js#L151-L155. Here are a list of API patch operations: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#patch-operations

I believe you'll want to use `application/json-patch+json`
You should have something like this:
```javascript
cores.ns.pod('my-awesome-pod').patch(
{  headers: { 'content-type': 'application/json-patch+json' } }, callback);
```

**Comment by shekharupland** [comment]
Yesss...This works. Thanks a ton for your help.. I will close this thread.
