### ISSUE TITLE
Document which API versions this client supports

### ISSUE THREAD

**Issue by sppatel** [godaddy/kubernetes-client#132]
It is not clear from the README which version of the kubernetes API this supports.  e.g 1.5, 1.6, 1.7

**Comment by silasbw** [comment]
Busted :grimacing: -- we do a horrible job of this right now, and have basically added endpoints to kubernetes-client without any versioning distinction.

Good news is we're working on fixing this via https://github.com/godaddy/kubernetes-client/issues/129, which should allow kubernetes-client users to specify an API version (or a swagger spec) and get an [API object](https://github.com/godaddy/kubernetes-client/blob/master/lib/api.js#L16) and resources that are specific to that version.

**Comment by silasbw** [comment]
We've done this.  5.X.X generates the client API bindings based off swagger specs.  We include specs for 1.7, 1.8, and 1.9.  You can also use the swagger.json you kube-apiserver serves, or a swagger file.
