### ISSUE TITLE
POST YAML rather than JSON?

### ISSUE THREAD

**Issue by philjones88** [godaddy/kubernetes-client#134]
I'm struggling to get POST'ing YAML to the deployments API working.

```
extensions.ns('test').deployments.post({
    headers: { 'content-type': 'application/yaml' },
    body: `
    apiVersion: extensions/v1beta1
    kind: Deployment ... `
});
```

I see if I alter the library to log out what options are generated:

```
{ headers: { 'content-type': 'application/json' },
  path: [ '/apis/extensions/v1beta1/namespaces/test/deployments' ],
  body: 'apiVersion: extensions/v1beta1\nkind: Deployment\n ...' }
```

How can I get this library to send the `application/yaml` header? I see the API documention for k8s says it' accepts YAML as their CURL example is YAML based.

https://kubernetes.io/docs/api-reference/v1.7/#-strong-write-operations-strong--20

And click curl for the example

**Comment by silasbw** [comment]
The kubernetes-client API expects `body` to be a JavaScript object (that is JSON serializable).  We didn't consider that a someone might want to send JSON or YAML, but I can imagine some scenarios where that'd be the case (*e.g.*, don't want to take a dependency on a YAML parser).

Can you help us understand why you'd like to use YAML (instead of JavaScript object)?

**Comment by philjones88** [comment]
well, our company started with k8s by writing YAML for each component we need to deploy then using `kubectl apply -f ....` to deploy to to k8s.

This has resulted in 21 different deployment/service/configmap etc that I'm now trying to automate via the API.

**Comment by silasbw** [comment]
That makes sense.  Our expectation was that users would be OK with doing something like:

```js
const yaml = require('js-yaml');
const jsonDeploy = require('./deploy.json');
const yamlDeploy = yaml.safeLoad(fs.readFileSync('./deploy.yaml'));

extensions.ns('test').deployments.post(jsonDeploy, ...);
extensions.ns('test').deployments.post(yamlDeploy, ...);
```

Would a pattern like that work for you?

**Comment by philjones88** [comment]
@silasbw we ended up with that but then had to fallback to raw `request` and well, we ended up just crafting everything ourselves as we're using Typescript async/await and we had to wrap this lib in promises. The lack of typings and documentation makes it hard to figure out the exact method chain as well...

**Comment by silasbw** [comment]
OK, I hear that and sorry for the pain.  I hope we're addressing that now with:

* Adding typings https://github.com/godaddy/kubernetes-client/issues/131, https://github.com/godaddy/kubernetes-client/compare/master...gisenberg:typings?expand=1
* Adding promise / async + await support https://github.com/godaddy/kubernetes-client/pull/133
* Adding the ability to generate API client from swagger specs https://github.com/godaddy/kubernetes-client/issues/129

I still don't completely understand your requirement around a string/YAML/JSON-based API vs the current object-based one.  That's something we could support if we understood the use case better.
