### ISSUE TITLE
OIDC Support

### ISSUE THREAD

**Issue by rjain15** [godaddy/kubernetes-client#135]
Does this client have support for OIDC, similar to the kubernetes dashboard code (https://github.com/kubernetes/dashboard/blob/master/vendor/github.com/coreos/go-oidc/oidc/client.go) 

I am using this javascript client and I am not sure if the instructions to authenticate using OIDC are clear in doc. 

thanks, Rajesh

**Comment by silasbw** [comment]
If you have an ID token, I believe you can set that like so:

```js
const core = new Api.Core({
  url: 'https://my-k8s-api-server.com',
  auth: {
    bearer: idToken
  }
});
```
We don't have any logic to refresh tokens, but would be interested in collaborating on implementing something.  I suspect you'd get mileage from leveraging one of the existing OIDC clients (*e.g.*, https://github.com/IdentityModel/oidc-client-js).

Can you share you use case?

**Comment by silasbw** [comment]
Re-open if you want to continue the discussion.
