### ISSUE TITLE
Unable to stream

### ISSUE THREAD

**Issue by sppatel** [godaddy/kubernetes-client#136]
When using the streaming example as documented in the readme I just get an error indicating that getStream is not a function.  

![k8s-client_js_ _platform-ui](https://user-images.githubusercontent.com/989367/28735466-463a3148-73b3-11e7-8e5c-d8166be5b268.png)

**Comment by sppatel** [comment]
Ah the problem is that the doc reflects what is in master rather then what is in the latest published release.

**Comment by jcrugzz** [comment]
@sppatel updated in latest version. but `get()` will still work as well :)
