### ISSUE TITLE
Update ConfigMap values

### ISSUE THREAD

**Issue by jingdongWang92** [godaddy/kubernetes-client#140]
How to update ConfigMap?

`api.group(json).ns.kind(json).put({ body:JSON.parse(JSON.stringify(json)) }, print);
`

the result like so:
`{ Error: the server does not allow this method on the requested resource}
`

**Comment by jeffpearce** [comment]
This should work:

`api.group.ns.configmaps('configmapname').put({ body:JSON.parse(JSON.stringify(json)) }, print);`

where `configmapname` is the name if your ConfigMap.

Let me know if you're still having problems

**Comment by silasbw** [comment]
Re-open if you want more help.
