### ISSUE TITLE
No passthrough of body on DELETE prevents cascading job deletes

### ISSUE THREAD

**Issue by AlexGilleran** [godaddy/kubernetes-client#143]
Right now [BaseObject.delete](https://github.com/godaddy/kubernetes-client/blob/master/lib/base.js#L81) doesn't pass through `body` - but the Kubernetes API uses the body for DELETEs, in particular when trying to do a cascading delete of orphaned pods belonging to a job:

https://github.com/kubernetes/kubernetes/issues/20902#issuecomment-321216843

Could DELETE be changed to pass through the body too?

**Comment by anton-kotenko** [comment]
Here is pull request that fixes this problem https://github.com/godaddy/kubernetes-client/pull/142

**Comment by AlexGilleran** [comment]
Oh nice, way ahead of me :).

**Comment by silasbw** [comment]
We merged @anton-kotenko's PR and released the changes via `kubernetes-client@3.15.0`.
