### ISSUE TITLE
Disconnecting from pod log stream

### ISSUE THREAD

**Issue by sandromello** [godaddy/kubernetes-client#145]
I'm facing a specific problem on aborting stream connections only with Google Chrome:

```
const kubeConf = (apiVersion, bearerToken) => {
  return {
    url: KUBERNETES_API_URL,
    version: apiVersion,
    request: {
      timeout: 300,
      gzip: true,
    },
    version: apiVersion,
    auth:{
      bearer: bearerToken
    }
  }
};
const kubecli { core: bearerToken => new kubernetesClient.Core(kubeConf('v1', bearerToken)) };
stream = kubecli.core('bearerToken').ns('mynamespace').pods('mypod').log.getStream({
  qs: { tailLines: 10, follow: true, container: 'mycontainer' }
});
stream.on('data', chunk => {
  console.log('CHUNK', chunk.toString());
});
// Doesn't work on Chrome
setTimeout(() => {
  console.log('ABORTING...')
  stream.abort();
}, 1000)
```

When I use the `stream.abort()` command `data` event stops and the connection keeps open until it reaches the timeout. However within Firefox the connection is closed properly.

I'm doing something wrong, or there's another way for aborting the request?

**Comment by silasbw** [comment]
DISCLAIMER: To be honest I haven't tested on Chrome or Firefox -- I'm a surprised you can get kubernetes-client to work on Firefox!  We have talked about providing better support for browsers and we are adding new features with that in mind (and have some work planned on cleaning up some things we know could cause issues).

With that, I think that you are closing the stream properly. I'm a little confused about your statement "When I use the stream.abort() command data event stops and the connection keeps open until it reaches the **timeout**."  Are you referring to the kube-apiserver connection timeout, or the timeout you're setting with `setTimeout`?

**Comment by sandromello** [comment]
Hi silas,
I'm using the client for a lot of kubernetes resources in a SPA application and it's working fine.
I mean the timeout from Kubernetes API Server.
This problem is a bit obscure and I'll try going deeper to understand what's going on.

Thank you for the follow up.

**Comment by silasbw** [comment]
Hey @sandromello any action here?  Is it worth keeping this issue open?

**Comment by sandromello** [comment]
Hi @silasbw, I tried to simulate the problem with the request library and it seems to have the same problem. I had success with the [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). If you don't plan to provide this kind of support to the library the issued could be closed.

**Comment by silasbw** [comment]
Documented the "support fetch" issue in https://github.com/godaddy/kubernetes-client/issues/234.
