### ISSUE TITLE
Stream status

### ISSUE THREAD

**Issue by shekharupland** [godaddy/kubernetes-client#147]
Is there a way to check if stream object returned by getStream is active or not. I would like to build start  and stop stream so looking for a consistent way to check the stream status.

**Comment by silasbw** [comment]
Hi @shekharupland -- can you use the stream events to do this (*i.e.*, https://nodejs.org/api/stream.html#stream_class_stream_readable)?  Or do you have example you can share where those won't work well?

**Comment by shekharupland** [comment]
sure, will try this and see if this helps. if this doesn't work I will share the code which I am trying to write.

**Comment by shekharupland** [comment]
I am able to make use of stream events. Thanks for the suggestion.
