### ISSUE TITLE
rs delete using match label is wrong,

### ISSUE THREAD

**Issue by freedomlee87** [godaddy/kubernetes-client#156]
ext.ns.rs.matchLabels({a:1}).delete()

rs is not deleted, but return all rs in cb functions

**Comment by silasbw** [comment]
Ah, you're right.  The Kubernetes API supports label matching only for read operations [1].  kubernetes-client in turn implements that same behavior.  We should at least update the README.md, and also consider updating the code so there's a more obvious error thrown when users try something like your example.

[1]: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
