### ISSUE TITLE
How to get status of pods?

### ISSUE THREAD

**Issue by DivyaYash** [godaddy/kubernetes-client#16]
When I do a k8.namespaces.replicationcontrollers.pod.get(print); Its a very long o/p..I am interested in knowing if the pod is in "Running" status or not..How can I fetch this information? 
Please help!

**Comment by silasbw** [comment]
@DivyaYash that short hand is useful when you want to get pods associated with a specific replication controller.  For example,

```
k8.ns('my-ns').rc.po.get('my-rc', print);
```

You can see what pods are running be inspecting that result:

```
function print(err, result) {
  if (err) return console.warn(err);
  // Interesting stuff about about the Pod                                                                                                                                                                                     
  const statuses = result.podList.items.map(pod => pod.status);
  // The phase the Pod is in (e.g., 'Running' or 'Terminating')                                                                                                                                                                
  const phases = statuses.map(status => status.phase);
  console.log(`Pod phases for RC ${ result.rc.metadata.name }:`);
  console.log(phases);
}
```

**Comment by DivyaYash** [comment]
Getting a Type error..
const statuses = result.podList.items.map(pod => pod.status);
                                 ^
TypeError: Cannot read property 'items' of undefined

**Comment by silasbw** [comment]
can you post the code you're running?

**Comment by DivyaYash** [comment]
Just copied urs and trying...am very new, do not know much ..
var fs = require('fs');
const K8Api = require('kubernetes-client');
const k8 = new K8Api({
  url: 'https://bfk8201:6443',
  version: 'v1',  // Defaults to 'v1'
  ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync('kubernetes-caasadmin-user.pem'),
  key: fs.readFileSync('kubernetes-caasadmin-user-key.pem'),
  namespace: 'netflow'
});
function print(err, result) {
  if (err) return console.warn(err);
  // Interesting stuff about about the Pod                                                                                                                                                                                     
  const statuses = result.podList.item.map(pod => pod.status);
  // The phase the Pod is in (e.g., 'Running' or 'Terminating')                                                                                                                                                                
  const phases = statuses.map(status => status.phase);
  console.log(`Pod phases for RC ${ result.rc.metadata.name }:`);
  console.log(phases);
}

k8.namespaces.replicationcontrollers.pod.get(print);

**Comment by silasbw** [comment]
Change this line:
```
k8.namespaces.replicationcontrollers.pod.get(print);
```
to include the name of the replication controller you're interested in.  For example, if you want to get all pods associated with your replication controller named 'foo-rc', you'd do:

```
k8.namespaces.replicationcontrollers.pod.get('foo-rc', print);
``` 

If you're interested in getting status for all the Pods in a namespace, just do:

```
function print(err, result) {
  const statuses = result.item.map(pod => pod.status);
  const phases = statuses.map(status => status.phase);
  console.log(phases);
}
k8.namespaces.pods.get(print);
```

**Comment by DivyaYash** [comment]
Thanks for the quick response, I am interested in status of all pods, I tried as you suggested, but getting error - const statuses = result.item.map(pod => pod.status);
                              ^
TypeError: Cannot read property 'map' of undefined
-----------------------------------------------------------
var fs = require('fs');
const K8Api = require('kubernetes-client');
const k8 = new K8Api({
  //url: 'http://9.45.125.92:8080',
  url: 'https://bfk8s01:6443',
  version: 'v1',  // Defaults to 'v1'
  ca: fs.readFileSync('ca.pem'),
  cert: fs.readFileSync('kubernetes-caasadmin-user.pem'),
  key: fs.readFileSync('kubernetes-caasadmin-user-key.pem'),
  namespace: 'bluecloud2'
  //namespace: 'netflow'
});

function print(err, result) {
  const statuses = result.item.map(pod => pod.status);
  const phases = statuses.map(status => status.phase);
  console.log(phases);
}
k8.namespaces.pods.get(print);

**Comment by DivyaYash** [comment]
Also, where can I know on "how to construct below calls"? which documentation I need to refer? 
k8.namespaces.pods.get(print);
result.item.map(pod => pod.status);
statuses.map(status => status.phase);

**Comment by silasbw** [comment]
sorry, I typoed:
```
function print(err, result) {
  const statuses = result.items.map(pod => pod.status);
  const phases = statuses.map(status => status.phase);
  console.log(phases);
}
```
(notice `items` instead of `item`)

For general JavaScript reference there's [MDN](https://developer.mozilla.org/en-US/)

For Kubernetes API documentation there's the [Kubernetes Docs](http://kubernetes.io/docs/api/).  E.g., here's the definition of the PodList which is the thing we're operating on above: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_podlist

Since this is more of JavaScript help question and less specific to `kubernetes-client`, I'm closing this again.

**Comment by DivyaYash** [comment]
Ok, thanks for your help, it worked!
The o/p seem to be listing some old non existing pods as well...The result of this call has a few pods in "Failed" status, however, when I check via kubectl get pods cmd, the results are different...
