### ISSUE TITLE
How patch working?

### ISSUE THREAD

**Issue by vforv** [godaddy/kubernetes-client#176]
Could you explain more about patch function?

Is it for the rolling update?

I tried it like this:

```
getK8SAPI(prod).namespaces.replicationcontrollers('http-rc').patch({
    body: patch
  }, (err, result) => {
    resultArr.push(result);
    res();
  })
```

What is `replicationcontrollers('http-rc')`?

```
{
    body: patch
  }
```

What should be inside body value? Any example? I need to update my current image how can I do that?

**Comment by jtslear** [comment]
I theorize that patch is supposed to be able to handle any type of patch that you can provide.  However, I'm kind of a plus one on this question?

I'm able to get the following `patch` object to work just fine:
```
  const patch = {
    "spec": {
      "replicas": 10
    }
  };
```
The deployment will scale up or down as necessary.

However, when I try to modify the desired image like so:
```
  const patch = {
    "spec": {
       "containers": [{
         "image": "image:some_diffferent_tag"
      }]
    }
  };
```
It doesn't appear to do anything... 🤔

**Comment by TWood67** [comment]
Hey @vforv, the patch function performs operations similar to `kubectl patch`:
https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_patch/
It wraps the `/patch` endpoint for each resource. 

`replicationcontrolls('http-rc')` is an operation against the replication controller resource with the name `http-rc`.

**Comment by TWood67** [comment]
@jtslear Could you try including the name field of the container you are trying to patch? According to the docs (https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_patch/) `name` is required when trying to update a container image.

**Comment by jtslear** [comment]
@TWood67 I tried to do this and I was still unsuccessful at getting the image updated.  Here's what I'm trying to accomplish (sanitized):

```js
const Api = require('kubernetes-client');

async function main() {
  const ext = new Api.Extensions(Api.config.fromKubeconfig())
  const patch = {
     "spec": {
       "containers": [{
         "name": "app",
         "image": "image:some_different_tag"
       }]
     }
  };
  await ext.namespaces('somespace').deployments('app').patch({
    body: patch
  }, print);
}

function print(err, result) {
  console.log(JSON.stringify(err || result, null, 2));
}

main();
```

**Comment by TWood67** [comment]
@jtslear Sorry for the late response. I'm guessing the body you are sending is incorrect. If you are patching a deployment, I believe it should look like:
```
{
  body: {
    spec: {
      template: {
        spec: {
          containers: []
        }
      }
    }
  }
}
```

See here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#create-21

**Comment by silasbw** [comment]
Hey @jtslear or @TWood67 :)

wanna add an example of using patch to update the image to [examples/](https://github.com/godaddy/kubernetes-client/tree/master/examples)?
