### ISSUE TITLE
Support for `exec`?

### ISSUE THREAD

**Issue by moltar** [godaddy/kubernetes-client#180]
Is there support for the `exec` method?

**Comment by robarago** [comment]
Hi, I would like to know the answer to this question too.

I'm interested in the `exec` method and also in file transfer methods (like `kubectl cp`) but, AFAIK, we this is implemented also with and `exec?command=tar`.

Regards.

**Comment by robarago** [comment]
Sorry, I've seen that [this thread](https://github.com/godaddy/kubernetes-client/issues/19) is related. We'd better lend a hand for this to happen.

Thanks for this great module, it's nicely engineered, very readable and worth collaborating for. Maybe I'll try ;-)

Is in active development?

**Comment by silasbw** [comment]
We have "experimental" support for `exec`.
