### ISSUE TITLE
Need networking management 

### ISSUE THREAD

**Issue by sebadiaz** [godaddy/kubernetes-client#182]
I use this code to replace inexisting code:

'use strict';

const ApiGroup = require('kubernetes-client/lib/api-group.js');

class Networking extends ApiGroup {
  constructor(options) {
    const resources = [
      'networkpolicies'
    ];
    options = Object.assign({}, options, {
      path: 'apis/networking.k8s.io',
      version: options.version || 'v1',
      groupResources: resources,
      namespaceResources: resources
    });
    super(options);
  }
}

module.exports = Networking;

**Comment by Paxa** [comment]
Thank you for sharing

**Comment by silasbw** [comment]
Do you want to send a PR for this @sebadiaz?

The (currently undocumented) swagger-gen code handles this.  I'm working on adding some documentation and rounding off some rough edges, so it's not quite ready for prime time.

**Comment by Paxa** [comment]
Also `certificatesigningrequests` not supported yet:

```js
class CertificateSigningRequests extends ApiGroup {
  constructor(options) {
    options = Object.assign({}, options, {
      path: 'apis/certificates.k8s.io',
      version: options.version || 'v1beta1',
      groupResources: [
        'certificatesigningrequests'
      ],
      namespaceResources: []
    });
    super(options);
  }
}

// config = { .. }
var client = new Api.Core(config);
client.csr = new CertificateSigningRequests(config).certificatesigningrequests;
client.certificatesigningrequests = client.csr;
```

**Comment by silasbw** [comment]
Both of these are supported in the newest version (see https://github.com/godaddy/kubernetes-client/blob/master/docs/1.7.md).
