### ISSUE TITLE
Fetch a specific namespace

### ISSUE THREAD

**Issue by austinkelleher** [godaddy/kubernetes-client#187]
Currently, the following yields every namespace:

```js
core.namespaces('mynamespace').get((err, data) => {
  // data contains every namespace
})
```

I can't seem to find the recommended method of searching for a specific namespace using the following API endpoint: `/api/v1/namespaces/mynamespace`

Thoughts @silasbw? Thanks in advance.

**Comment by silasbw** [comment]
Yikes!  Thanks @austinkelleher.  I implemented it in https://github.com/godaddy/kubernetes-client/pull/190.  It will probably get merged and included with a major release in the next couple of days.
