### ISSUE TITLE
Api.config.fromKubeconfig TypeScript definition incorrectly?

### ISSUE THREAD

**Issue by guesslin** [godaddy/kubernetes-client#197]
I'm trying to run the sample code in TypeScript like
```typescript
import * as Api from 'kubernetes-client';
....
this.core = new Api.Core(Api.config.fromKubeconfig());
```

but got errors while build the code

```
kubernetes-deployer.ts|16 col 34 error| 2554[QF available]: Expected 1-2 arguments, but got 0
```

is this typesctipt definition correctly?
https://github.com/godaddy/kubernetes-client/blob/master/typings/index.d.ts#L61

or the question mark is missed after `kubeconfig` ?

**Comment by silasbw** [comment]
Stale issue (TypeScript support has been re-written).
