### ISSUE TITLE
Is this client supporting the batch group ?

### ISSUE THREAD

**Issue by Overdrivr** [godaddy/kubernetes-client#198]
It is unclear from the documentation whether or not this client supports the `batch` group (more specifically I am interested in the [job v1 batch](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#job-v1-batch) endpoints). Is this the case ?

**Comment by gergelyke** [comment]
Hi @Overdrivr !

Yes, it does: https://github.com/godaddy/kubernetes-client/blob/a4708cc24f6d29930d32aa6d12b4e07885c42765/lib/batch.js#L15

Let us know if you need further help!
