### ISSUE TITLE
Watch Pod stream ends immediately if config is missing version: 'v1/watch'

### ISSUE THREAD

**Issue by Overdrivr** [godaddy/kubernetes-client#199]
I am watching a pod for changes, using the following code:

```
const core = new k8s.Core({
...
});

// Logs are limited to 10 kB
const jsonStream = new JSONStream();
const stream = core.ns('default')
  .pod(podId)
  .getStream({ qs: {
    watch: true,
    includeUninitialized: true,
    timeoutSeconds: 60 * 10,
  }});

stream.pipe(jsonStream);

jsonStream.on('data', function(pod) {
  console.log('Pod has changed: %o', JSON.stringify(pod));
});

jsonStream.on('end', function() {
  console.log('Pod stream has ended');
});
```

My logs show that as soon as the `data` event is called, the stream is ended. I only receive the initial state of the pod (`ContainersNotReady`).

However, GCloud console shows that after a few seconds, the pod's container boots properly and runs properly, meaning that more events were available but never received.

After some investigation, I realized that for the stream to keep running, the configuration must contain `version: 'v1/watch'`. Is this normal behavior ?

Code that works:
```
const core = new k8s.Core({
   version: 'v1/watch',
});
// rest is the same than above
```

BTW my kubernetes master version is 1.8.

Important: Make sure to test this on a particular pod. The problem is not there when watching for all pods (`version: 'v1/watch'` is missing, but the streams stays open in that case)

**Comment by silasbw** [comment]
Yeah, that's a bug/missing feature related to our inability to manually keep up with Kuberentes API improvements :(

However :), we have undocumented code that generates a client dynamically based off of the swagger spec.  It needs a little polish and documentation, but it's almost there.

**Comment by silasbw** [comment]
We've released these improvements.  Check out the new README.md and try it out.  If problems persist, let us know.
