### ISSUE TITLE
Incorrect AuthorizationConfiguration Typescript type definition

### ISSUE THREAD

**Issue by bkon** [godaddy/kubernetes-client#200]
The type definition here (https://github.com/godaddy/kubernetes-client/blob/master/typings/index.d.ts#L12) implies that in order to use password-based auth, we need to provide an object with the following structure:

```
auth: {
  user: {
    username,
    password
  }
}
``` 

README gives a different example:

```
auth: { 
  user,
  pass
}
```

which seems to match data requirements by `request` npm module which is use by kubernetes-client under the hood.

Suggested fix: remove the local AuthorizationConfiguration definition and instead of that re-export AuthOptions from `@types/request` under this alias.

**Comment by silasbw** [comment]
Should be fixed.
