### ISSUE TITLE
Support for 'rollout undo' deployment

### ISSUE THREAD

**Issue by daseyffert** [godaddy/kubernetes-client#204]
I am curious if there is any feature with this client that takes advantage of kubectl rollout undo command?

If there isn't, any guidance on being able to implement this feature would be very helpful as well.

I am dealing with Kubernetes version 1.7 and 1.8.

**Comment by silasbw** [comment]
I'm not sure how that's implemented, but in theory it should be implementable using the Kubernetes API via kubernetes-client.  This isn't an issue with kubernetes-client specifically, but it would be useful to include this as an example.

If you end up implementing this, can you share the code with us so we can include it as an example?

**Comment by daseyffert** [comment]
I wasn't able to figure it out using kubernetes-client so I ended up implementing a different way.

In order to roll back you need to run a POST command to the url path: 
/apis/extensions/v1beta1/namespaces/<! NAMESPACE>/deployments/<! DEPLOYMENY>/rollback

The body of the POST command looks as follows:
var postBody =
        {
            "kind": "DeploymentRollback",
            "apiVersion": "extensions/v1beta1",
            "name": <! NAME_OF_YOUR_DEPLOYMENT>,
            "rollbackTo":
                {
                    "revision": <! REVISION_NUM_YOU_WANT_TO_ROLLBACK_TO>
                }
        };

Hope this is useful.
