### ISSUE TITLE
Cert error

### ISSUE THREAD

**Issue by debianmaster** [godaddy/kubernetes-client#21]
Getting this error while connecting.    how can i fix this?
```sh
{
  "code": "SELF_SIGNED_CERT_IN_CHAIN"
}
```

**Comment by andrewklau** [comment]
You should load your ca like mentioned in the README or use this `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` although not recommended..

**Comment by debianmaster** [comment]
this is for dev purpose only.  thanks for the pointer

**Comment by gajus** [comment]
@andrewklau This no longer works.

We have an internal proxy that logs all requests.

Is there a new configuration?

I have also tried `insecureSkipTlsVerify` with no success.

**Comment by gajus** [comment]
Never mind. I was setting `insecureSkipTlsVerify` as a direct property of `Client` configuration. Instead, it should have been a property of the kubeconfig.
