### ISSUE TITLE
Not able to create namespace in 4.0.1, but the same code works fine in 3.18.1

### ISSUE THREAD

**Issue by UtkarshYeolekar** [godaddy/kubernetes-client#211]
We have a wrapper written around k8's client. The code was working fine previously for creating namespace, but the same code didn't work, if i update the kubernetes client version to 4.0.1.

How to reproduce: 

**In 3.18.1 --> Working Code**

//Initialize k8s object
const k8s = new Api.Api({
    url: 'http://localhost:8000'
})

k8s.group("v1")**.ns()**.post({ body: nsJson });

And it will create a namespace.

if i use the same code with the 4.0.1, it will throw the error that:
**Error: the server does not allow this method on the requested resource**

In 4.0.1 ---> Working Code

I have just little modified the above code, instead of passing the empty parathesis, for the **ns()**, i have added the single quotes in it and it worked **ns('')**.

const k8s = new Api.Api({
    url: 'http://localhost:8000'
})

k8s.group("v1").**ns('')**.post({ body: nsJson });

Don't know, whether this is a bug, or the intended functionality in 4.0.1

**Comment by silasbw** [comment]
@UtkarshYeolekar can you try this:

```js
const k8s = new Api.Api({
url: 'http://localhost:8000'
})

k8s.group("v1").ns.post({ body: nsJson });
```

This is how we intend users to create namespaces.  Previously, the namespace create behavior was buggy (resulting in workarounds like `k8s.group("v1").ns().post({ body: nsJson });`).  Sorry about that.  Let us know how the above suggestion works for you.

**Comment by UtkarshYeolekar** [comment]
Thanks @silasbw ,

The above suggestion works for me.
