### ISSUE TITLE
Add support for all CRD names

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#216]
The current swagger client supports only the `plural` name for CRDs.  Extend the client to support `singular` and `shortNames` too.  Using `example/using-crds.js` and `example/crontabs-crd.json`:

```js
// Plural usage, currently supported
await client.apis['stable.example.com'].v1.namespaces('default').crontabs.get();
// Singular (needs support)
await client.apis['stable.example.com'].v1.namespaces('default').crontab.get();
// shortNames (needs support)
await client.apis['stable.example.com'].v1.namespaces('default').ct.get();
```

See https://github.com/godaddy/kubernetes-client/blob/master/lib/swagger-client.js and https://kubernetes.io/docs/concepts/api-extension/custom-resources/ for more information.

**Comment by VaibhavPage** [comment]
I can take a stab at it.

**Comment by silasbw** [comment]
That would be great :hot_pepper: !
