### ISSUE TITLE
`/watch` / streaming API example

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#219]
Add an example to examples/ demonstrating calling a `/watch` endpoint, and setting up the Node.js streams.

**Comment by XVincentX** [comment]
I'd be interested in that. I've dug into the code a bit and, at least in 1.5, I can't find any way to append a custom endpoint so I can watch the changes by myself. I do not even find a `watch` method.

Although an example would be appreciated, could you at least point me towards the right direction?

**Comment by XVincentX** [comment]
I figured it out with a bit of intuition.

`client.apis.apps.v1beta.watch.namespaces('default').deployments('dep').getStream(…)` will do the trick. Just add the `watch` part before querying the resource you're interested.

Keep up with the great work!

**Comment by silasbw** [comment]
Thanks @XVincentX ... any chance you have a few minutes to PR an example using watch?  We'd appreciate it :)  You would add it to https://github.com/godaddy/kubernetes-client/tree/master/examples

**Comment by XVincentX** [comment]
Yeah sure, I'll try to have a look during the following days!
