### ISSUE TITLE
Getting public IP address for a service

### ISSUE THREAD

**Issue by darweshsinghcgi** [godaddy/kubernetes-client#245]
I'll keep this short and simple: when I run `curl -X GET http://127.0.0.1:8001/api/v1/namespaces/default/services/service` I get the `ingress ip` for the service (assuming it's a `loadBalancer` .

When I run `const service = await client.apis.v1.namespaces('default').services('service').get();` I get the following:

```
Getting service:  { statusCode: 200,
  body:
   { kind: 'Service',
     apiVersion: 'v1',
     metadata:
      {...},
     spec:
      { ports: [Array],
        selector: [Object],
        clusterIP: '10.11.243.137',
        type: 'LoadBalancer',
        sessionAffinity: 'None',
        externalTrafficPolicy: 'Cluster' },
     status: { loadBalancer: [Object] } } }
```

And the last line is where the public IP address should be returned. Is there some way to return the actual IP address as part of this?

(on GKE)

**Comment by silasbw** [comment]
Do you mean `status: { loadBalancer: [Object] } } }`?  It looks like you might be using `console.log(service)` and you're getting the object reference and it sounds like you want the value \[[1]\].

Instead, do:

```js
console.log(JSON.stringify(service, null, 2));
```

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Console/log
