### ISSUE TITLE
Typings do not match current interface

### ISSUE THREAD

**Issue by RobertDiebels** [godaddy/kubernetes-client#249]
The Typecript index.d.ts does not reflect the 5.2.0 interface.
KubernetesClient.Client is missing.

**Comment by silasbw** [comment]
Yeah, we need to add this and it's high on the priority list.  If someone wants to help out, the high-level approach would be:

1. Add client classes for the existing swaggers specs in [lib/specs](https://github.com/godaddy/kubernetes-client/tree/master/lib/specs).  E.g., add a Client class to `lib/client-1.7`:
```js
const SwaggerClient = require('./swagger-client');
module.export = class Client extends SwaggerClient {
  constructor() {
    super({ version: '1.7' });
  }
};
```
2. Add a `typings.js` script similar to the [docs](https://github.com/godaddy/kubernetes-client/blob/master/scripts/docs.js) one that generates typings for a specified swagger spec and the associated static clients defined in 1.
3. Generate typings for the included swagger specs in [lib/specs](https://github.com/godaddy/kubernetes-client/tree/master/lib/specs) and commit them.

**Comment by jeffmaury** [comment]
I am trying to use the bindings from a VSCode extension for OpenShift but did not manage to find the solution. Is this related to this one as well ?

**Comment by silasbw** [comment]
Yep -- do you have some time to help out :)?

**Comment by jeffmaury** [comment]
Yes no pb

**Comment by RobertDiebels** [comment]
@silasbw I believe I read something about a typescript generator for the OpenAPISpec a while ago maybe that would be a direction investigate? Could possibly save you some time.

**Comment by silasbw** [comment]
It would, but it doesn't generate very "fluent" names for the API calls.  The names basically end up being the Operation ID which are pretty unwieldy and don't map well to the kubernetes reference documentation.  I discuss this more is https://godaddy.github.io/2018/04/10/an-intuitive-nodejs-client-for-the-kubernetes-api/.

Qualitatively I like the API naming conventions that kubernetes-client uses (e.g., `client.api.namespaces('foo').pods('goo').get()`, but it comes at the cost of writing our own generators.
