### ISSUE TITLE
Help getting a basic client up and running

### ISSUE THREAD

**Issue by emileae** [godaddy/kubernetes-client#265]
I'm not sure this is the best place to ask this, but I'm looking for some help implementing kubernetes-client on an express server.

```
app.get('/k8/godaddy', (req, res) => {

  var host = req.query.host;
  var username = req.query.username;
  var pw = req.query.pw;

  const Client = require('kubernetes-client').Client
  const client = new Client({
    config: {
      url: host,
      auth: {
        user: username,
        pass: pw,
      },
      insecureSkipTlsVerify: true,
    }
  });

  var nameSpaces = client.api.v1.namespaces.get();
  console.log("nameSpaces --> ", nameSpaces);
});
```

the host variable is just an IP address, something like this 35.xx.xxx.xx
username and password are definitely correct. I don't think there is actually a problem getting authenticated, since a client object exists.

The error I get is "**TypeError: Cannot read property 'v1' of undefined**", So there's no client.api...

When I check the properties of the client object I get the following:

`[ 'templatedEndpoints', 'parameter', 'splits', 'http' ]`

My cluster is running on Google Kubernetes Engine, so the cluster IP, username and password are all fairly easy to get hold of (at least as far as I can tell).

Any help would be greatly appreciated, also if this is the wrong place to ask for this kind of help, feel free to close the issue.

**Comment by ajpauwels** [comment]
If you look at the Client constructor here: https://github.com/godaddy/kubernetes-client/blob/052e00c57ac1a5832f131717e1c63f50e3e26bdd/lib/swagger-client.js#L346

you can see what it needs to build out the API client from the swagger config file it has. Looks like you're missing the `version` key, which should exist alongside `config`. You should be able to put in `'1.7'`, `'1.8'`, or `'1.9'` in there to make it work.

**Comment by emileae** [comment]
Ah, ok, thanks for the pointer, I should be on the right track now. Much appreciated.

**Comment by silasbw** [comment]
Any suggestions on how we might improve our docs on this one?

**Comment by emileae** [comment]
I think it's less a case of improving the docs and more of me getting to grips with the swagger docs.
