### ISSUE TITLE
Logs for multi-container pod

### ISSUE THREAD

**Issue by VaibhavPage** [godaddy/kubernetes-client#267]
I am trying to get logs for a pod that has multiple containers running inside it, basically something like kubectl logs xxx --all-containers=true.  Is there a way I can achieve this with the client?

**Comment by silasbw** [comment]
Should be possible, but thb I never done it.  See the `container` query parameter:

https://github.com/godaddy/kubernetes-client/blob/master/docs/1.7.md#apiv1namespacesnamespacepodsnamelogget

(basically the same as the documentation here: https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#read-log)

When you get it working, can you post your snippet here?  or better, add an example to `examples/`?

**Comment by VaibhavPage** [comment]
Can you review my PR?

https://github.com/godaddy/kubernetes-client/pull/272
