### ISSUE TITLE
Is there a plan to support apiserver version 1.10?

### ISSUE THREAD

**Issue by subhankarc** [godaddy/kubernetes-client#286]
Hello,

Currently, the specs only supports till apiserver version 1.9.

Is there a plan to extend support for 1.10 as well?

**Comment by battlecow** [comment]
Have you tried using the client with a 1.10 cluster, it appears to be working as intended for me without any added configuration when using inCluster config.

**Comment by silasbw** [comment]
It's supported:  https://github.com/godaddy/kubernetes-client#initializing (see the `loadSpec` example).

I can generate the docs and add the swagger to this repo, if that's helpful.

**Comment by subhankarc** [comment]
Yes that would be helpful. I’ll then give it a try.

**Comment by silasbw** [comment]
Published to npm as 5.3.1. Give it a try and let us know how it goes.
