### ISSUE TITLE
Watch for longer duration

### ISSUE THREAD

**Issue by subhankarc** [godaddy/kubernetes-client#294]
Hi,

We want to run a process which waits for a longer amount of time. The code looks like this.

``` javascript

registerWatcher(callback, queryString) {
    return Promise.try(() => apiserver.loadSpec())
      .then(() => {
        const stream = apiserver
          .apis['deployment.servicefabrik.io'].v1alpha1.watchnamespaces('default').directors.getStream({
            qs: {
              labelSelector: queryString ? queryString : ''
            }
          });
        const jsonStream = new JSONStream();
        stream.pipe(jsonStream);
        jsonStream.on('data', callback);
        jsonStream.on('error', err => {
          logger.error('Error occured during watching', err);
          throw err;
        });
      })
      .catch(err => {
        return buildErrors(err);
      });
  }
```

If we want to re-register the watch, what is the best way to do it? One option we are thinking is to call the function multiple times, using a setInterval. In that case, how do we cancel the previous watch, or do we not need to take care of that?

Any pointers on the same would be helpful.

**Comment by silasbw** [comment]
What do you mean about "waiting for a longer amount of time"?  The kube-apiserver will periodically disconnect watch streams intentionally, so you need to handle that and reconnect when it happens.

**Comment by subhankarc** [comment]
Currently I am re-registering the watcher in every 20 mins aborting the current stream and creating a new one. I chose 20 mins as I found in the documentation that min time for keeping the watch is 1800 seconds, 30 mins. 

However, I’m  ot sure if this is the right way. Hence I want to know if this is what is intended or is there a better way to do this?

**Comment by silasbw** [comment]
We use a pattern like this for some internal projects we're working on open sourcing:

```js
function watcher(options) {
  const stream = client.apis['deployment.servicefabrik.io'].v1alpha1.watchnamespaces('default').directors.getStream()
  stream.on('end', () => {
    watcher(options);
  });
  const jsonStream = new JSONStream();
  stream.pipe(jsonStream);

  jsonStream.on('data', event => {
    // Do stuff
  });
}
```

It might be an improvement over what you're doing because it does depend on a hard-coded value.

**Comment by subhankarc** [comment]
Thanks @silasbw . This can also be then done for the error I guess, so that for any error as well it re-establishes the watch. 

```javascript
        jsonStream.on('error', err => {
          logger.error('Error occured during watching', err);
          watcher(options);
        });
```

**Comment by silasbw** [comment]
Yeah, that's a good suggestion.  You'll probably want to inspect the error to ensure it's something you could expect to recover from, or add some backoff time.  Otherwise you might be getting 404s, for example, and end up retrying requests when it's unlikely they'll eventually succeed.

If you end up writing some code to handle this, we'd love it if you could contribute some of it to [examples](https://github.com/godaddy/kubernetes-client/tree/master/examples).

**Comment by subhankarc** [comment]
Thanks. Sure, will create a PR.
