### ISSUE TITLE
get nodes and get specific node, both results are the same.

### ISSUE THREAD

**Issue by sayyes566** [godaddy/kubernetes-client#296]
api.v1.nodes(name).get 
api.v1.nodes.get 
all list:

{
"statusCode": 200,
"body": {
"kind": "NodeList",
"apiVersion": "v1",
"metadata": {
"selfLink": "/api/v1/nodes/",
"resourceVersion": "0000"
},
"items"
...

**Comment by silasbw** [comment]
Oh no, that sounds like a bug.  Do you have any time to investigate?  even better would be a PR to fix it :)

**Comment by tkporter** [comment]
@sayyes566 Any idea what version of kubernetes you're getting this issue with? I was unable to reproduce this with version 1.8

**Comment by sayyes566** [comment]
I used v1.10.3

**Comment by sayyes566** [comment]
Ok. This was not a bug.
I tried those APIs and return different json.

My nodes
NAME          STATUS    ROLES     AGE       VERSION
kube-master   Ready     master    76d       v1.11.1
kube-node-1   Ready     <none>    76d       v1.10.4
