### ISSUE TITLE
Load CRD via kubernetes api?

### ISSUE THREAD

**Issue by fentas** [godaddy/kubernetes-client#300]
I want to utilize an existing CRD (`voyager.appscode.com) within a Kubernetes pod.
Judging from this example
https://github.com/godaddy/kubernetes-client/blob/master/examples/using-crds.js
CDRs are generally supported.

The question is if `kubernetes-client` is able to load the definition by itself (crawling through `apis`)? Or do I have to pass it manually via json file?

e.g. 
```sh
curl [...] https://kubernetes.default/apis/voyager.appscode.com/v1beta1/
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "voyager.appscode.com/v1beta1",
  "resources": [
    {
      "name": "ingresses",
      "singularName": "ingress",
      "namespaced": true,
      "kind": "Ingress",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "ing"
      ]
    },
    {
      "name": "certificates",
      "singularName": "certificate",
      "namespaced": true,
      "kind": "Certificate",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "cert"
      ]
    }
  ]
}
```

Here my code example
```js
const {Client, config} = require('kubernetes-client')
const k8s = new Client({
  config: config.getInCluster(),
  version: '1.10'
})
k8s.loadSpec().then(client => {
  // undefined
  console.log(client.apis['voyager.appscode.com'])
}).catch(err => {
  logger.error(err)
})
```

_edit:_ After downloading the swagger file I am able to load it like this
```
k8s._addSpec(JSON.parse(fs.readFileSync('/swagger/voyager.appscode.com.json')))
```

**Comment by silasbw** [comment]
kubernetes-client doesn't currently add the CRD endpoints automatically and you'll need to do it manually.  The expectation was that you'd have the CRD manifest file (and use https://github.com/godaddy/kubernetes-client/blob/master/examples/using-crds.js#L23).

For your use case, where did you download the swagger file from? Did you get it from Voyager GitHub repo, or the kube-apiserver (if so, I didn't realize this was supported for CRDs), or somewhere else?  It sounds like we should better support your use case.

**Comment by fentas** [comment]
I downloaded it directly from voyagers repo. \
https://github.com/appscode/voyager/blob/master/api/openapi-spec/swagger.json

But I can imagine that the Kubernetes API gives enough information by itself. The swagger file is kind of redundant considering the API server output (see above).

Crawling to all endpoints on startup could be too expansive (time to load) but something like this would be nice.

```js
// e.g. loadSpec, loadEndpoint or loadResource (or simalar)
async function run () {
  await k8s.loadSpec('/apis/voyager.appscode.com/v1beta1/')
  let ingresses = await k8s.apis['voyager.appscode.com'].v1beta1.namespaces('default').ingresses.get()
  console.log(ingresses)
}
run()
```

**Comment by silasbw** [comment]
Potential approach (see `1.`): https://github.com/godaddy/kubernetes-client/issues/426#issuecomment-469977089

**Comment by fentas** [comment]
tanks. :+1:
