### ISSUE TITLE
convert to typescript? 

### ISSUE THREAD

**Issue by xmlking** [godaddy/kubernetes-client#304]
official  `kubernetes-client` is already converted to typescript.
can we convert this project to `ts` and build and distribute as `js` lib?
we can get rid of maintaining types and support both typescript and javascript users.

**Comment by silasbw** [comment]
Would an up-to-date declaration file work for you?  if not, let us know why.

A motivation for keeping the code a js is that we expect it facilitates a broader set of potential contributors (more folks know js, than ts).  What do you think about that?

**Comment by xmlking** [comment]
Ya updating typedefs should be good for now. Only  problem is, maintence of those types and keeping  them in sync is a pain. 
As more developers are moving towards ts, and strong typing helps to avoid compile  errors ,I feel moving to TS is a good investment for long term. I might be able to contribute  with refactoring code and adding build tools if needed

**Comment by silasbw** [comment]
We'd love that.  We'd make updating the typedefs automatic.  Similar to how generate the client bindings right now is automatic.

**Comment by silasbw** [comment]
I realize there's some nagging issue with the declaration file, but those are tracked with other issues.  I'm going to close this under the assumption that an up-to-date declaration file is an OK way to support typescript and js users.
