### ISSUE TITLE
Please support AWS Authenticator for EKS

### ISSUE THREAD

**Issue by spiffytech** [godaddy/kubernetes-client#306]
Amazon EKS requires the user generates a token through the AWS Authenticator, using the `exec` option on the user property in the kubeconfig file. kubernetes-client does not appear to support this option, so we cannot use it to talk to our EKS clusters.

https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html

**Comment by silasbw** [comment]
We need to support this.  We're also planning on adopting EKS.

**Comment by cfellin1** [comment]
On it.
