### ISSUE TITLE
Simplest example to test getInCluster auth method

### ISSUE THREAD

**Issue by bakso** [godaddy/kubernetes-client#330]
I am writing a nodejs web sever which is running in the pods and it should be able to call api to delpoy apps into others pods on the same cluster.  

But the privilege got by getInCluster is not enough and caught error.

Could you offer some example or docs about user/rbac/privilege to test my feature of creating deploys/srevices/ingress. Thx.

**Comment by bakso** [comment]
```
Error: deployments.apps is forbidden: User "system:serviceaccount:default:default" cannot create deployments.apps in the namespace "default"
    at http.request (/usr/src/app/node_modules/fluent-openapi/lib/loader.js:230:25)
    at Request.request [as _callback] (/usr/src/app/node_modules/kubernetes-client/lib/request.js:108:14)
```

**Comment by silasbw** [comment]
I wrote this working toy example a while back: https://github.com/silasbw/kubernetes-badges.

https://github.com/silasbw/kubernetes-badges/blob/master/kubernetes-badges.yaml might be useful.

Does that help 'ya?

**Comment by Xalip** [comment]
Did you ever solve this issue? How can I tell the InCluster Client to use a service account?
