### ISSUE TITLE
Unhandled rejection when request-promise is present in node_modules

### ISSUE THREAD

**Issue by jBouyoud** [godaddy/kubernetes-client#345]
I observe some `Unhandled rejection` on my project. 
After investigations, this will come from interaction between `request-promise` and your library.
Issue is located in this file : https://github.com/godaddy/kubernetes-client/blob/master/lib/request.js

Since request promise override the prototype of `request` and return a promise which is rejected when statusCode is not 2xx.

To fix this you can do something like 
```
 const res = request(requestOptions, (err, res, body) => {
 ....
 if (res && typeof res.catch === 'function') {
    res.catch(err => cb(err));
 }
```
in https://github.com/godaddy/kubernetes-client/blob/master/lib/request.js L154-176.

This is an edge case that why I don't open a PR.
For my use case, I overwrite the request method of the `Request` class and give this new class instance to the client `http` options.

**Comment by silasbw** [comment]
Thanks -- you should still open a PR :heart: :smile:

**Comment by spk83** [comment]
Looks like this is fixed by changes made in this PR - https://github.com/godaddy/kubernetes-client/pull/370
