### ISSUE TITLE
Authentification on the k8S cluster

### ISSUE THREAD

**Issue by julien-hedoux** [godaddy/kubernetes-client#347]
Hi, 

I try to connect the client to my cluster but I don't find how to create a login/password account in the cluster. 
In your sample, you put : 
````
config: {
        url: process.env.K8S_CLUSTER_HOST,
        auth: {
          user: process.env.K8S_USER,
          pass: process.env.K8S_PASSWORD
        },
        insecureSkipTlsVerify: true
````
But how do you create an account with the password in the k8s cluster? 

Thank you for your help

**Comment by silasbw** [comment]
This is out of scope for kubernetes-client and depends on how you've setup your cluster.  There are a couple of ways to control this through your [kubeapi-sever](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), but how that is setup is largely dependent on what provider or tools you're using to create you cluster.
