### ISSUE TITLE
Replace loadSpec URL to new OpenAPI spec

### ISSUE THREAD

**Issue by ajpauwels** [godaddy/kubernetes-client#352]
According to this link, the old swagger endpoints are deprecated as of Kubernetes 1.10:
https://kubernetes.io/docs/concepts/overview/kubernetes-api/#openapi-and-swagger-definitions

`loadSpec` should call `/openapi/v2` with appropriate headers.

It may be a good idea to implement this as using `/openapi/v2` primarily, and to fallback to the old URL in case the cluster has an old version of Kubernetes.

I can probably knock this out this weekend.

**Comment by ajpauwels** [comment]
Just realized this is dependent on the `fluent-openapi` module and not any code here, should I close this, or am I mistaken?

**Comment by silasbw** [comment]
Well, that's an embarrassing artifact from the refactor.  I addressed it with https://github.com/godaddy/kubernetes-client/pull/353.  Let's keep this issue here, and we'd love it if you want to contribute that implementation you outlined, @ajpauwels .
