### ISSUE TITLE
Break the generated documentation markdown into separate files

### ISSUE THREAD

**Issue by tammersaleh** [godaddy/kubernetes-client#362]
Github is cowardly refusing to render the 1.8MB markdown files 😢 Would it be possible to break them up along API boundaries so each one is small enough to be rendered?

![kubernetes-client 2018-11-14 16-12-18](https://user-images.githubusercontent.com/2016/48521185-3e846500-e828-11e8-9b78-9989e3d86110.png)

**Comment by silasbw** [comment]
yep, we need to do this.  Do you have any suggestions on where the break points should be?

**Comment by tammersaleh** [comment]
One file per resource probably makes the most sense (output from `kubectl api-resources -o name`, for example)

Also, I should have said thanks earlier for providing this great library - very useful!
