### ISSUE TITLE
{url}/openapi/v2  receive a 403 error

### ISSUE THREAD

**Issue by ymedlop** [godaddy/kubernetes-client#363]
Hi,

The last version of this library doesn't work with my cluster definition ( Openshift 3.7).

When We try to get the Api definition from {url}/openapi/v2  we receive a 403 error.

I saw this commit:

https://github.com/godaddy/kubernetes-client/commit/8a5f5cb46408f87bdd1b5687efb5b7e52b9df9b5

Could it be possible to support more code error in addition to 404 ?

Thanks in advance

**Comment by ajpauwels** [comment]
A 403 can't be resolved by the library, it indicates you don't have the required permissions for the request. However, I'm confused as to why the `/openapi/v2` would require any permissions, as it should be an open endpoint.

A couple questions:
1. What version of k8s is your cluster at?
2. What do you see when manually navigating to the `/openapi/v2` endpoint in your browser?
3. What do you see when navigating to the `/swagger.json` endpoint in your browser?

**Comment by ajpauwels** [comment]
Weird...never seen that before. We can change the logic to fallback to `swagger.json` on any error and then forward the error if the old route doesn't resolve either.

I likely won't get around to it until later in the week, feel free to do it yourself if you've already written a wrok-around, I'll post here when the PR goes in.

**Comment by ajpauwels** [comment]
PR to address the issue can be found here: https://github.com/godaddy/kubernetes-client/pull/364
