### ISSUE TITLE
Client call hung for no clear reason

### ISSUE THREAD

**Issue by siyangy** [godaddy/kubernetes-client#367]
We have a piece of code like:
`response = await client.apis.batch.v1.namespaces(namespaceId).jobs.post({ body: jobParam });`

However, very rarely the call just didn't return and made our node program stuck forever. This might be due to a server hiccup but the client should timeout / return an error accordingly. I am wondering if there's any config I can specify to avoid this?

**Comment by silasbw** [comment]
@siyangy you can try specifying a shorter timeout.  For example:

```js
const config = ... // however you generate your config.  E.g., config.fromKubeconfig()
const timeout = 10000 // milliseconds
const client = new Client({ config: { timeout, ...config }})
```
