### ISSUE TITLE
Exception when retrieving an empty log from a Pod

### ISSUE THREAD

**Issue by qlikbez** [godaddy/kubernetes-client#376]
When I try to get the logs from a pod `client.api.v1.namespaces("default").pods(<name>).log.get();` and that pod has no log an exception has been thown from the `request.js`.
` return body.status === 'Failure' &&
              ^
TypeError: Cannot read property 'status' of undefined
`
This is because in this case the HTTP response has a status 200 with a empty response body (undefined), so the check in `isUpgradeRequired` fails.
Please upgrade the function `isUpgradeRequired` adding a check if the body is defined:
`return body && body.status === 'Failure' &&`

**Comment by silasbw** [comment]
Let us know if `kubernetes-client@6.6.1` fixes this issue for you.
