### ISSUE TITLE
Latest version of swagger-fluent has verbose errors

### ISSUE THREAD

**Issue by weikinhuang** [godaddy/kubernetes-client#391]
I just updated `kubernetes-client` to latest and it brought in a newer version of swagger-client.

The client is printing out in my logs every time I make a request to the kubernetes api:

```
Component / already has a Path Item Object
```

Looks like swagger-fluent was updated 5 days ago:

https://github.com/silasbw/swagger-fluent/blob/master/lib/loader.js#L204

**Comment by silasbw** [comment]
Thanks @weikinhuang -- I'm looking at this right now.

**Comment by silasbw** [comment]
Published fix with `kubernetes-client@6.7.1`
