### ISSUE TITLE
How to stop watch?

### ISSUE THREAD

**Issue by joolfe** [godaddy/kubernetes-client#399]
Hi,

I'm using the watch to see the status of a Job in kubernetes with some code like this:

```
const stream = client.apis.batch.v1.watch.namespaces(namespace).jobs(jobNode.metadata.name).getStream();
	    const jsonStream = new JSONStream()
	       stream.pipe(jsonStream)
	    jsonStream.on('data', event => {
	      console.log('---- Event: ', event.type);
	      console.log(event.object.status);
	      console.log('---- END ----');
	      if( event.type == 'MODIFIED'){
	      	if( event.object.status.hasOwnProperty('completionTime')  ){
	      		console.log("--- JOB COMPLETE ---");
	      		console.log(stream);
	      		stream.destroy();
	      		jsonStream.destroy();
	      	}
	      }
	    })
```

When the job is complete i want to close the stream and free resources but everything that i have test is not working :-( how can i stop the stream??

Best Regards.

**Comment by silasbw** [comment]
Take a look at this example: https://github.com/godaddy/kubernetes-client/blob/master/examples/watch.js

Does that approach work for you?

**Comment by silasbw** [comment]
Re-open if the example code doesn't work for 'ya.
