### ISSUE TITLE
Console log flooded with "Component ... already has a Path Item Object"

### ISSUE THREAD

**Issue by kundralaci** [godaddy/kubernetes-client#400]
Hi there!

I am about to use the latest (6.8.1) typescript version, but I end up receiving a lot of console messages that I don't understand:

```
Component /apis/apps/v1/namespaces/dev already has a Path Item Object
Component /apis/apps/v1/namespaces/dev already has a Path Item Object
Component /apis/apps/v1/namespaces/dev already has a Path Item Object
Component /apis/apps/v1/namespaces/dev already has a Path Item Object
```

To be precise, I get 4 of these messages each time I make a call to get deployments in a namespace, that I do regularly:
```
const deployments = await this.client.apis.apps.v1.namespace('dev').deployments.get();
```
It also happens on most kinds of API requests. I init this way:
```
import * as K8S from 'kubernetes-client';
const K8SClient = K8S.Client1_10;
const K8Sconfig = K8S.config;
const client = new K8SClient({ config: K8Sconfig.fromKubeconfig() });
client.loadSpec().then(() => { ... });
```

I also found that these messages are coming from swagger-fluent@3.1.1, exactly from here: https://github.com/silasbw/swagger-fluent/commit/8a04b387c0627eb36a86c597a2c5322ec93dce55

I just don't understand whether my code is wrong, or is it a real issue?

Thank you very much in advance!

*UPDATE:*
I see it has been solved in a previous version (#391 ), but with the latest mentioned version, I face this problem again.

**Comment by silasbw** [comment]
Yuck.  I'm looking at it now.  Thanks for reporting.

**Comment by silasbw** [comment]
Doh, don't call `loadSpec()` (that shouldn't even be included in the declaration file).

I'll work to remove `loadSpec()` from the declarations, but for now simply remove that call. I'll leave this open to track the work update the declaration file.

**Comment by silasbw** [comment]
`kubernetes-client@6.8.2` includes the newest declaration file with `.loadSpec()` removed.

**Comment by kundralaci** [comment]
Ouh, i see!

Thank you very much for the clarification! Now it works like charm!
