### ISSUE TITLE
How to specify a context?

### ISSUE THREAD

**Issue by sbyrne-sugarcrm** [godaddy/kubernetes-client#407]
I am using version 6.8.1.  In my use case, I have several different contexts defined in my ~/.kube/config file.  It appears that kubernetes-client likes to use the one listed as the current context.  However, during my work day, I am constantly switching which my current context is, and I would like to be able to force the context used by my kubernetes-client code to be a specific one.  I realize that I could load  the config file "by hand" extract out the full set of settings for the context that I want, and use the "in memory" path of invoking fromConfig, but I'm thinking there must be a more direct way to achieve what I want.  

I saw the the CONTEXT env var is documented for use when running tests, so I tried that for my app, but it appears to be ineffective when used outside of the testing context.

**Comment by silasbw** [comment]
Thanks for the suggestion @sbyrne-sugarcrm.  Created a PR to document the option.
