### ISSUE TITLE
deployments function not available?

### ISSUE THREAD

**Issue by mergingseas** [godaddy/kubernetes-client#408]
I am testing the api by trying to get the the currently active services and deplyments,

I have the following code:

```
const Client = require('kubernetes-client').Client;
const config = require('kubernetes-client').config;

const path = process.env.HOME+'/.kube/config';

async function main () {
	try {
		
		const client = new Client({
			  config: config.fromKubeconfig(path),
			  version: '1.9'
		});
		//console.log(client);
	    const functions = await client.api.v1.namespaces('default')
	    console.log(functions);
	    
	    const services = await client.api.v1.namespaces('default').services.get();
	    console.log(services)
	    
	    const pods = await client.api.v1.namespaces('default').pods.get();
	    console.log(pods);
	    
	    const deployments = await client.api.v1.namespaces('default').deployments.get();
	    console.log(deployments);
	}
	 catch (err) {
		    console.error('Error: ', err)
	}
}

main();
```

I succesfully get the services and the pods but I get an exception on the deployments.

On further investigation deployment doesn't seem to be part of the children list of the namespace;

children: 
   [ 'pods',
     'po',
     'pod',
     'services',
     'svc',
     'service',
     'replicationcontrollers',
     'rc',
     'replicationcontroller',
     'resourcequotas',
     'quota',
     'resourcequota',
     'persistentvolumeclaims',
     'pvc',
     'persistentvolumeclaim',
     'podtemplates',
     'podtemplate',
     'configmaps',
     'cm',
     'configmap',
     'secrets',
     'secret',
     'serviceaccounts',
     'serviceaccount',
     'endpoints',
     'ep',
     'endpoint',
     'events',
     'ev',
     'event',
     'limitranges',
     'limits',
     'limitrange',
     'bindings',
     'binding',
     'finalize',
     'status' ],

**Comment by silasbw** [comment]
Deployments are part of the Kubernetes apps/v1 API, not the Kubernetes api/v1 API.

This should work:

```js
await client.apps.v1.namespaces('default').deployments.get();
```

Also, see https://github.com/godaddy/kubernetes-client/blob/master/examples/basic.js
