### ISSUE TITLE
feature request - support for verticalpodautoscaler

### ISSUE THREAD

**Issue by naseemkullah** [godaddy/kubernetes-client#426]
Hi there,
Thanks for this amazing client.
Can support for vertical pod autoscalers please be added?

TIA

**Comment by silasbw** [comment]
kubernetes-client supports it.  See the docs.  E.g., https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/HorizontalPodAutoscaler.md

**Comment by silasbw** [comment]
.... and let me know if you're having trouble with it :)

**Comment by naseemkullah** [comment]
Thanks @silasbw but the link provided is for horizontal pod autoscaler. i am looking to create/delete vertical pod autoscaler manifests.

https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

**Comment by justinasfour04** [comment]
I was looking for exact same support for the vertical-pod-autoscaler. The link provided the top points to Horizontal Pod Scaling and not Vertical. This would be a great feature to have

**Comment by silasbw** [comment]
Doh, I'm an idiot.  Re-opening.

**Comment by silasbw** [comment]
Right now kubernetes-client facilitates this with [.addCustomResourceDefinition](https://github.com/godaddy/kubernetes-client/blob/master/examples/using-crds.js#L23): you need to pass in the CRD manifest for the [`VerticalPodAutoscaler`](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/vpa-beta2-crd.yaml#L2).

In the future, Kubernetes is planning on extending CRDs to support updating the swagger/openapi spec.  When that happens `await client.loadSpec()` will be sufficient for access the APIs added by CRDs.  Until this it's manual.

Two more things:
1. if you have ideas on how to make this easier, I'd be open to discussing them (one half-baked thought is to add a `client.loadCustomResourceDefinitionSpecs()` method that fetches all the CRD objects from the Kubernetes API and extends the client accordingly).
2. in the short term, if you feel like you have enough context from above to unblock yourself, I'd encourage you to add an example specifically for `VerticalPodAutoscaler` to [examples/](https://github.com/godaddy/kubernetes-client/tree/master/examples).

Hope this helps.  Happy to discuss more about short term and long term issues.

**Comment by justinasfour04** [comment]
So passing the CRD manifest to the addCustomResourceDefinition function worked out and we were able to add Vertical Pod Scaling. For the time being, the process is either manual to add single CRD objects to the client instance. Or your half-baked idea of extending the client given the results of the fetch from the K8s API. I can give it a shot and try adding a function that further extends the client after the swagger specs are defined

**Comment by naseemkullah** [comment]
Hi @silasbw ,

In the meantime I've created a (PR to include a vpa specific example)[https://github.com/godaddy/kubernetes-client/pull/428]. Please have a look, thanks!

**Comment by silasbw** [comment]
We have a short term example for VPAs (thanks @naseemkullah!): https://github.com/godaddy/kubernetes-client/tree/master/examples/vpa

Let's continue the long term discussion here: https://github.com/godaddy/kubernetes-client/issues/426
