### ISSUE TITLE
watch example not working

### ISSUE THREAD

**Issue by davehorton** [godaddy/kubernetes-client#432]
This did not work for me, as this line:

https://github.com/godaddy/kubernetes-client/blob/a6d8dba5f7bc74e71b35ed3e71a2acd862cc4b6e/examples/watch.js#L42

needed to be updated (for me at last) to 
```js
const stream = client.api.v1.watch.namespaces..
```

**Comment by silasbw** [comment]
Thanks for the report @davehorton.  Created https://github.com/godaddy/kubernetes-client/pull/434 to address.
