### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by Ravikiran1992** [godaddy/kubernetes-client#448]
According to you, kubernetes-client translates Path Item Objects [1] (e.g., /api/v1/namespaces) to object chains ending in HTTP methods (e.g., api.v1.namespaces.get).
So, to fetch all Namespaces:
const namespaces = await client.api.v1.namespaces.get()

So how do we use it for /apis/metrics.k8s.io/v1beta1/namespaces/{namespaceName}/pods , which already has "." in it

**Comment by silasbw** [comment]
In JavaScript you need access properties with dots in them using bracket notation.  E.g.,

```js
const pods = await client.apis['metrics.k8s.io'].v1beta1.namespaces('my-app').pods.get()
```
