### ISSUE TITLE
how run kubeclt command?

### ISSUE THREAD

**Issue by inyee786** [godaddy/kubernetes-client#450]
i want to run some kubectl command

eg `kubectl describe po <pod name>`
     `kubectl get <custom resource> -n namespaces`

**Comment by silasbw** [comment]
Check out the [examples](https://github.com/godaddy/kubernetes-client/tree/master/examples) and documentation for the specific object you're interested in (*e.g.*, [Pods](https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/Pod.md#apiv1namespacesnamespacepodsnameget)).

**Comment by SamDecrock** [comment]
I was looking for the equivalent of `describe` too, but it turns out kubectl does multiple API calls to get this information.
