### ISSUE TITLE
Can't stream pod logs

### ISSUE THREAD

**Issue by Mokto** [godaddy/kubernetes-client#469]
Hi,

It seems it's not possible to stream logs from a pod. I run this code when the phase of the pod becomes `Running`:

```
  const stream = K8S.client.api.v1.namespaces(config.namespace).pods(podName).log.getStream({
    qs: { tailLines: 10, follow: true }
  });
  const jsonStream = new JSONStream()
  stream.pipe(jsonStream)

  jsonStream.on('data', (data: any) => {
    console.log(data);
  });
```

No log is ever outputted.

Thanks !

**Comment by silasbw** [comment]
what is your log output format?  If it's not newline delimited JSON then `JSONStream` might be buffering your logs.  If that's the case, try dropping the `JSONStream` code.

**Comment by Mokto** [comment]
That was it ! Many thanks!

For reference, this is how I did it : 

```

  const stream = k8s.client.api.v1
    .namespaces(config.namespace)
    .pods(podName)
    .log.getStream({
      qs: { follow: true },
    });

  stream.on('data', (data: any) => {
    console.log(data.toString('utf8').replace(/\n/g, ''));
  });
```

I hope it will help someone!
