### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by tj-kev** [godaddy/kubernetes-client#512]
Is there a way to specify a custom header when sending requests to the Kubernetes API?

I have a particular use case which needs to protect the remote API endpoint with an access key in a header (x-api-key for example).

This would be separate from the traditional authentication methods. Just a way to get past a firewall rule.

Can't see a way to do it from looking through the code. Just checking i'm not missing something.

Thanks

**Comment by silasbw** [comment]
Yes, you can pass a `headers` object to any of the REST verb functions.  E.g.,

```js
await client.apis.apps.v1.namespaces('default').deployments(name).patch({ body, headers: { 'content-type': 'application/merge-patch+json' });
```
