### ISSUE TITLE
openid-client requires node version >=12.0.0

### ISSUE THREAD

**Issue by Cruzercru** [godaddy/kubernetes-client#518]
I am trying to install kubernetes-client using yarn and it throws and error when installing the openid-client dependency as it requires a node version of 12 or later. According to the package file,  kubernetes-client is supposed to support node version 8 or later. The current openid-client version required by kubernetes-client is 3.1.0 and will require a downgrade to version 2 to continue support for anything earlier than node version 12.

**Comment by silasbw** [comment]
Include your suggested change with `kubernetes-client@8.3.2`

**Comment by panva** [comment]
When `kubernetes-client` drops support for Node 8 due to its upcoming EOL `openid-client@^3.5.0` now supports node lts/dubnium as well (^10.13.0 || >=12.0.0)
