### ISSUE TITLE
Metric server api using metric server support?

### ISSUE THREAD

**Issue by RaghebAD** [godaddy/kubernetes-client#519]
I can't find documentation on how to get metrics of a pod or a node. 
kubectl top node
kubectl top pod

**Comment by silasbw** [comment]
You'll need a swagger specification for the metrics server and then you can extend your client instance with `_.addSpec(spec)`.  If you do it successfully, we'd love a PR to https://github.com/godaddy/kubernetes-client/tree/master/examples.
