### ISSUE TITLE
`watch` on custom resources ends after an indeterminate amount of time.

### ISSUE THREAD

**Issue by craicoverflow** [godaddy/kubernetes-client#520]
When watching a custom resource, the stream automatically closes after an inconsistent and indeterminate amount of time.

```js
const fooStream = kubeclient.apis['test.api.group'].v1alpha1.watch
    .namespaces('test')
    .foo.getStream();

const fooJsonStream = new JSONStream();
fooJsonStream.pipe(fooStream);
fooJsonStream.on('data', () => {
  console.log('data changed');
});

fooJsonStream.on('end', () => {
  console.log('stream closes automatically');
});
```

**Comment by silasbw** [comment]
Is this only for CRDs?  It should be happening for every type of resources you watch.  It's expected behavior of the kube-apiserver (see `--min-request-timeout` https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

**Comment by craicoverflow** [comment]
Hi @silasbw - yes it is only happening on CRDs. I actually came to the realisation  that this also happens outside of this kubernets-client, so this can be closed.
