### ISSUE TITLE
Missing support for some object types

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#53]
clusters, petsets, quota (not resourcequotas/'quota') and replicasets.

**Comment by ankon** [comment]
For Petset have a look at https://github.com/Collaborne/kubernetes-client/tree/collaborne. This name is deprecated though, so I'm currently preparing a PR to support StatefulSet instead: https://github.com/Collaborne/kubernetes-client/tree/collaborne-3.1.0

The other types can probably get added in a similar way.

**Comment by silasbw** [comment]
Awesome!  Looking forward to your PR.

**Comment by ankon** [comment]
@silasbw out of interest: do you have documentation pointers to the "cluster" and "quote" resources?

**Comment by silasbw** [comment]
I got those names out of an older version of [1] and meant to follow up on documentation.  I suspected "quota" was a bugo and it looks like it was removed [2].  I think it's safe to ignore my comment about the distinction between "quota" and "resourcequotas/quota".

[1]: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L172
[2]: https://github.com/kubernetes/kubernetes/commit/ffcc2f61b55a166b21d3e4af3d4c6d97696cf1b6
