### ISSUE TITLE
`kubectl apply -f` functionality

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#64]
From @therynamo:

"Another nicety would be being able to do something like kubectl apply -f, programatically. So instead of seeing, Error: deployment "insert_deployment_name_here" already exists, it would just overwrite with the new config. However, I may have yet again misread the docs."

**Comment by cfellin1** [comment]
I'm interested in looking into this @silasbw.

**Comment by cfellin1** [comment]
RE apply, this seems to get the job done:

```
const deploymentManifest = require('./nginx-deployment.json')
client.apis.apps.v1.namespaces('default').deployments('nginx-deployment').put({ body: deploymentManifest });
```

Though please correct me if this doesn't hold up.

**Comment by cfellin1** [comment]
Though I suppose it has the downside of working exclusively for replace and not working for create in the way `apply` does.

**Comment by silasbw** [comment]
Yeah, what about adding a pattern to `examples/`?  Something like:

```js
try {
  await client.apis.apps.v1.namespaces.post(...);
} catch (err) {
  if (err.code !== 409) throw err;
  await client.apis.apps.v1.namespaces.put(...);
}
```

I'm reluctant to include it in the `kubernetes-client` library because it would be introducing a "high-level wrapper" to what is currently a pretty straightforward REST API wrapper.
