### ISSUE TITLE
Jobs API endpoint

### ISSUE THREAD

**Issue by thataustin** [godaddy/kubernetes-client#66]
This may be an inquiry more than a request, but I'm trying to use this library to list/create a job in my cluster.

According to [these docs](https://kubernetes.io/docs/api-reference/batch/v1/operations/), the correct api endpoint is: 
`GET /apis/batch/v1/namespaces/{namespace}/jobs/{name}`.

When I use this library like so (assuming the namespace configured in the k8 constructor is `my-namespace`:
`k8.namespace.jobs('my-job').get(a => console.log(a));`

It makes a request to:

`/api/v1/namespaces/my-namespace/jobs/my-job`

How do I get the first part of that url be `/apis/batch/v1/namespaces`?  Is there a setting I'm missing somewhere?

Thanks, and I appreciate all the work you've done on the library so far!

**Comment by jcrugzz** [comment]
@thataustin this would need https://github.com/godaddy/kubernetes-client/pull/57 to be merged in order to have the correct `batch` `ApiGroup`

**Comment by thataustin** [comment]
Kinda what I figured based on how it seems to be auto-magically constructing the url from the attribute references.

Here's to merging #57 🍺
