### ISSUE TITLE
Cannot watch events endpoint

### ISSUE THREAD

**Issue by cainelli** [godaddy/kubernetes-client#68]
Hello! I'm trying to watch the events endpoint but the request it's not sending the `watch=true`. query string, 

Here's how I'm doing it:

```
const JSONStream = require('json-stream');
jsonStream = new JSONStream();

const stream = k8.ns('myns').events.get({ qs: { watch: true } });
jsonStream.on('data', res => {
  // handling response
});
```

<img width="1434" alt="screen shot 2017-02-02 at 19 35 30" src="https://cloud.githubusercontent.com/assets/3514984/22569823/223de8ec-e980-11e6-8b1e-93770bad0fe5.png">

**Comment by silasbw** [comment]
Are you missing `stream.pipe(jsonStream);` ?

I'd expect this to work:

```
const JSONStream = require('json-stream');
const jsonStream = new JSONStream();

const stream = k8.ns('myns').events.get({ qs: { watch: true } });
stream.pipe(jsonStream);
jsonStream.on('data', res => {
  // handling response
});
```

https://github.com/godaddy/kubernetes-client#watching-and-streaming

**Comment by cainelli** [comment]
I miss that on the issue description but I didn't on the code. However, it's working now and I have no idea what I've messed up.

I'm having another trouble to end the streaming though. What would be the proper way to disconnect from k8s when watching or following endpoints?

Thank you.

**Comment by cainelli** [comment]
OK, I think I figured that out.

```
stream.abort();
```

**Comment by srossross-tableau** [comment]
Are there any recent examples of this? I can't seem to find any resources on streaming events.

**Comment by silasbw** [comment]
Yeah, there's some discussion in Issue https://github.com/godaddy/kubernetes-client/issues/219 and en example in PR https://github.com/godaddy/kubernetes-client/pull/241
