### ISSUE TITLE
Deprecated Types Warning

### ISSUE THREAD

**Issue by TWood67** [godaddy/kubernetes-client#79]
There should be a warning when users use a deprecated type. However there needs to be a 'type x version' matrix before this can be implemented.

From @jcrugzz on implementing this:
"Not a bad idea. The only tricky part is that deprecation depends on what k8s version the user is using. We should be showing a support matrix for types and k8s version after this merges"

Initial suggestion in #78

**Comment by silasbw** [comment]
5.X.X should mostly address this need: it generates the client based on a swagger spec.
