### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by silasbw** [godaddy/kubernetes-client#81]
The requirements and expectations for potential contributors should be clear.

- We use https://github.com/conventional-changelog/standard-version
- Angular-style commit messages (for standard-version) https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

**Comment by MichaelTSS** [comment]
Yes I'd love to contribute and such a file would help!

**Comment by silasbw** [comment]
Sure, I can try to get this done in the next couple of days...you can help review the PR :)

In the meantime, do you have any questions about contributing that I can answer?

**Comment by MichaelTSS** [comment]
Great!

I believe Node.JS has such a section. If you want to start contributing, simple non-urgent issues are listed for new contributors to get started quickly.
For programmers that want to be more involved, a list of features that should be built (or refactoring to be made) would be helpful. And as you mentioned, guidelines would be great too.
