### ISSUE TITLE
Support for --all-namespaces

### ISSUE THREAD

**Issue by nick** [godaddy/kubernetes-client#93]
Is there a way to get resources over all namespaces? I couldn't see an obvious way, unless I'm missing something.

**Comment by silasbw** [comment]
No, kubernetes-client doesn't have a built in way.  Here's **a** way.  If you come up with something you feel good about, please share it.  We'd be interested in adding it, but we don't have a concrete use case right now and haven't had the time to think about what kind of API would make sense.  If you have a good use case to help guide the API, that would be helpful.

```js
const async = require('async');
const Api = require('kubernetes-client');
const core = new Api.Core(Api.config.fromKubeconfig());

function getAll(resource, cb) {
  core.ns.get((err, res) => {
    if (err) return cb(err);
    async.map(
      res.items,
      (obj, next) => core.ns(obj.metadata.name).kind(resource).get(next),
      cb);
  });
}

getAll('pods', (err, res) => {
  console.log(err, res);
});
```

**Comment by nick** [comment]
Thanks for that Silas. My use case is a monitoring app that lists all pods on the system and their associated resources (services, persistent volumes, etc). Each 'app' has its own namespace. I was thinking we could use the existing `ns` method but perhaps with a * to indicate all namespaces:

    core.ns('*').po.get(print);

**Comment by debianmaster** [comment]
is there any solution yet for  watching all namespace?  for events like pod creation etc.

**Comment by silasbw** [comment]
@debianmaster the solution for watching is implemented.  This issue is about replicating (`kubectl --all-namespaces`)  If you want to watch Pod events across all namespaces, for example:

```js
const Api = require('kubernetes-client');
const core = new Api.Core(Api.config.fromKubeconfig());
const JSONStream = require('json-stream');
const jsonStream = new JSONStream();

const stream = core.pods.get({ qs: { watch: true }});
jsonStream.on('data', object => {
  console.log('Pod:', JSON.stringify(object, null, 2));
});
stream.pipe(jsonStream);
// NB: don't forget to handle disconnects!

```

**Comment by debianmaster** [comment]
thanks @silasbw  awesome!

**Comment by theothermike** [comment]
same use-case for me, thanks for the quick turn-around!  Turns out, kube-system pods sometimes have issues, and would want to know about any of them changing state, so this simplifies things greatly for me

**Comment by anuiq** [comment]
@silasbw Has this been implemented for the extensions as well. For example, if I want to get all replicasets across all namespaces?

**Comment by debianmaster** [comment]
@anuiq   yes  as far as i know

**Comment by debianmaster** [comment]
@anuiq  yes as far as i know

**Comment by anuiq** [comment]
@silasbw Can I use this for the extensions API? I want to get all the deployments and replica sets. 
const async = require('async');
const Api = require('kubernetes-client');
const core = new Api.Core(Api.config.fromKubeconfig());

function getAll(resource, cb) {
  core.ns.get((err, res) => {
    if (err) return cb(err);
    async.map(
      res.items,
      (obj, next) => core.ns(obj.metadata.name).kind(resource).get(next),
      cb);
  });
}

getAll('pods', (err, res) => {
  console.log(err, res);
});

This is what I was using for deployments: 
const async = require('async');
const Api = require('kubernetes-client');
const ext = new Api.Extensions(Api.config.fromKubeconfig(Api.config.loadKubeconfig('./kubeconfigs/'+req.params.stage+'-'+req.params.dc)));

function getAll(resource, cb) {
  ext.ns.get((err, res) => {
    if (err) return cb(err);
    async.map(
      res.items,
      (obj, next) => ext.ns(obj.metadata.name).kind(resource).get(next),
      cb);
  });
}

getAll('deployments', (err, res) => {
  console.log(err, res);
});

I want to use something similar for replica sets as well. Any input will be appreciated. Thank you

**Comment by silasbw** [comment]
Seems like an OK approach @anuiq.

**Comment by silasbw** [comment]
I'm really late replying to https://github.com/godaddy/kubernetes-client/issues/93#issuecomment-288742940 @nick, but I don't like the `core.ns('*').po.get(print);` approach because it looks like it follows the currently established pattern, but usages like `core.ns('*').po.delete()` probably wouldn't make sense.  I'd lean more towards adding something like `core.getAll('pods')` or `core.utils.getAll('pods')` or something.

@jcrugzz do you have any thoughts?

**Comment by silasbw** [comment]
This isn't something we'll support.  We've converged on supporting a JavaScript API client for the Kubernetes API.  There are other "high-level" libraries for JavaScript out there that would be good candidates for this (e.g., https://github.com/ajpauwels/easy-k8s)
