### ISSUE TITLE
PODS cleaned up for replication controllers, but not for jobs and deployments

### ISSUE THREAD

**Issue by bnevis-i** [godaddy/kubernetes-client#95]
When deleting a replication controller, the replica count of the pods is set to zero before the deletion. However, when deleting jobs and deployments, they job/deployment is deleted while leaving existing pods running.

**Comment by silasbw** [comment]
Thanks for calling this out.

We were considering removing automatic Pod deletion / scale down on ReplicationController `delete` in favor of propagationPolicy (see [1] and [2]).  This would simplify kubernetes-client and result in less surprising semantics.  You should be able to use propagationPolicy now if you're running a recent Kubernetes version.

[1]: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
[2]: https://kubernetes.io/docs/api-reference/v1.6/#delete-24

**Comment by silasbw** [comment]
@bnevis-i i'm going to close this -- feel free to re-open if you think propoagationPolicy isn't going to work for you.
